### ISSUE TITLE
[bug]  Issue number not automatically appended in multi-line commit messages

### ISSUE THREAD

**Issue by haruyam15** [byulhook/byul#12]
### 🐞 Description

When using the multi-line commit method, the issue number is not being appended automatically.

### 💻 Bug Simulation

1. Use the git commit command to create a multi-line commit message.
2. Observe that the issue number is not automatically appended at the end of the commit message.

**Comment by theconomicat** [comment]
vim으로 커밋 메세지를 작성할때 기존 커밋 메세지 탬플릿에 포함된 주석 때문에 커밋메세지 뒤에 설정된 타입과 이슈번호가 주석처리 되고 있습니다
