### ISSUE TITLE
[bug] Windows: 'chmod +x .husky/commit-msg' Command Does Not Work

### ISSUE THREAD

**Issue by theconomicat** [byulhook/byul#4]
### 🐞 Description

The chmod +x .husky/commit-msg command, which is used to make the .husky/commit-msg file executable, does not function in a Windows environment. This is because chmod is a Unix-based command and is not natively supported on Windows systems.

### 💻 Bug Simulation

1.	Run the command chmod +x .husky/commit-msg in a Windows environment.
2.	Observe that the command fails to execute or is not recognized by the system.
3.	Attempt to use attrib -r +a .husky/commit-msg as an alternative, but it does not replicate the expected outcome of making the file executable.

**Comment by badaclockA** [comment]
If you're a Windows user, use `git bash shell` and it should work!
https://gitforwindows.org/

**Comment by theconomicat** [comment]
attrib -r +a .husky/commit-msg
