### ISSUE TITLE
[bug] Husky Required for 'npm install byul' Setup on Fresh Install

### ISSUE THREAD

**Issue by theconomicat** [byulhook/byul#5]
### 🐞 Description

When running npm install byul in a project where Husky has not been pre-installed, the setup does not complete successfully. This is because the Husky dependency is necessary for Byul’s Husky hooks to be properly configured.

### 💻 Bug Simulation

1.	In a fresh project without Husky installed, run npm install byul.
2.	Observe that the setup related to Husky hooks does not complete as expected.
3.	Notice that without pre-installing Husky, the necessary Husky hooks for Byul are not set up, leading to a broken or incomplete configuration.

**Comment by badaclockA** [comment]
You can do a husky init and then npm install byul.

```bash
npx husky init
```

After entering this command
```bash
npm install byul
echo 'node ./node_modules/byul/dist/index.js "$1"' > .husky/commit-msg
chmod +x .husky/commit-msg
echo '{"byulFormat": "{type}: {commitMessage} #{issueNumber}"}' > byul.config.json
```
