### ISSUE TITLE
[fix] 유효하지 않은 API키일 때 커밋 중단시키는 로직 추가, husky일 때 추가 로직

### ISSUE THREAD

**Issue by badaclockA** [byulhook/byul#71]
### 각종 버그 수정
- OPENAI_API_KEY가 잘못되었을 때 오류 메시지를 출력하고 커밋을 중단시키게 하기
-  .husky/prepare-commit-msg에 setup.js 실행시 커밋훅이 추가되게 수정하기

### byul을 잠시 끄고 커밋을 하고 싶을 때를 위한 옵션 추가
`.env`에 BYUL_ALL_OFF=true 를 하면 byul을 끄고 커밋을 할 수 있도록함.
![image](https://github.com/user-attachments/assets/b9936e28-1f63-4b19-9723-8e09e75cc9b4)

### ✅ Tasks

- [x] OPENAI_API_KEY가 잘못되었을 때 오류 메시지를 출력하고 커밋을 중단시키게 하기
- [x] .husky/prepare-commit-msg에 setup.js 실행시 커밋훅이 추가되게 수정하기

**Comment by nakyeonko3** [comment]
![image](https://github.com/user-attachments/assets/5a050b86-aaa5-451c-851d-589b03230c4a)

**Comment by badaclockA** [comment]
![image](https://github.com/user-attachments/assets/017ef22a-20d7-40a4-8b18-0e47ab34b3c5)

**Comment by nakyeonko3** [comment]
![image](https://github.com/user-attachments/assets/9b9986fe-9bc6-4809-8ef3-5cdf2b587c48)
